# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20181018_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200),
        ),
    ]
