# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20181018_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200),
        ),
    ]
