"""
Django settings for bookmarks project.

Generated by 'django-admin startproject' using Django 1.11.16.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
from django.urls import reverse_lazy

from .base import (ALLOWED_HOSTS, AUTH_PASSWORD_VALIDATORS,  # noqa: F401
                   AUTHENTICATION_BACKENDS, BASE_DIR, DATABASE_FILE_NAME,
                   DATABASES, DJANGO_APPS, EMAIL_BACKEND, LANGUAGE_CODE,
                   LOGIN_REDIRECT_URL, LOGIN_URL, LOGOUT_URL, MEDIA_ROOT,
                   MEDIA_URL, MIDDLEWARE, ROOT_URLCONF, SECRET_KEY, STATIC_DIR,
                   STATIC_ROOT, STATIC_URL, STATICFILES_DIRS, TEMPLATES,
                   TEMPLATES_DIR, TIME_ZONE, USE_I18N, USE_L10N, USE_TZ,
                   WSGI_APPLICATION)

DEBUG = True

THIRD_PARTY_APPS = [
]

LOCAL_APPS = [

]

INSTALLED_APPS = LOCAL_APPS + THIRD_PARTY_APPS + DJANGO_APPS

# Google Consumer Key
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '385964686943-gohrfhihuc5c5t1vpcoj86l7t9b11ouh.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'bzM7gqU3SMomMwJa3txcPlKV'  # Google Consumer Secret

SOCIAL_AUTH_REDIRECT_IS_HTTPS = False

ABSOLUTE_URL_OVERRIDES = {
    'auth.user': lambda u: reverse_lazy('user_detail',
                                        args=[u.username])
}
